spring.application.name=loans
# DB in memory used due to lack of time
spring.datasource.url=jdbc:h2:mem:loandb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Create tables automatically based on @Entity
spring.jpa.hibernate.ddl-auto=update

# To see the DB in the browser
spring.h2.console.enabled=true